accounts/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('register', views.register,name='register'),
]

gymweb/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from register import views as v


urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('register/',v.register, name="register"),
    path("",include("django.contrib.auth.urls"))
    
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home,name='home'),
    path("ceny",views.ceny, name="ceny"),
    path("food",views.food, name="food"),
    path("training",views.training, name="training"),
    path("formy",views.formy, name="formy"),
    path("<int:id>",views.food_user, name="food_user"),
    path("onas",views.onas, name="onas"),
    path("zaregistrujse",views.zaregistrujse, name="zaregistrujse"),
]

accounts/models.py
from django.db import models

# Create your models here.

main/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Jidelnicek(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="jidelnicek",null=True)
    name = models.CharField(max_length=200)

    def __str__(self): #rozšifruje str
        return self.name


class Jidla(models.Model):
    jidelnicek = models.ForeignKey(Jidelnicek, on_delete=models.CASCADE)
    text = models.CharField(max_length=300)

    def __str__(self): #rozšifruje str
        return self.text

register/models.py
from django.db import models

# Create your models here.

register/forms.py
from django import forms
from django.contrib.auth import login, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User

class RegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

accounts/views.py
from django.shortcuts import render

# Create your views here.

def register(request):
    return render(request,"Registrace.html")

main/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect
from .models import Jidelnicek, Jidla

# Create your views here.

def home(response):
    return render(response,"main/base.html")

def ceny(response):
    return render(response,"main/ceny.html")

def food(response):
    return render(response,"main/food.html")

def formy(response):
    return render(response,"main/formy.html")

def training(response):
    return render(response,"main/training.html")

def food_user(response, id):
    ls = Jidelnicek.objects.get(id=id)
    return render(response,"main/food_user.html",{"ls":ls})

def onas(response):
    return render(response,"main/onas.html")

def zaregistrujse(response):
    return render(response,"main/zaregistrujse.html")
    
    

register/views.py
from django.shortcuts import render, redirect
from .forms import RegisterForm

# Create your views here.
def register(response):
    if response.method == "POST":
        form = RegisterForm(response.POST)
        if form.is_valid(): #jestli je vše vyplněné
            form.save() #ulož user
        
        return redirect("/")
    else:
        form = RegisterForm()

    return render(response,"register/register.html",{"form":form})

main/templates/main/base.html
{% load static %}
{% static "images" as baseUrl %}
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>{% block title %}VAPE-G{% endblock %}</title>
    <link rel="icon" type="static image/png" href="{% static 'images/Favicon.png' %} "/>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <!-- Google fonts -->
    <link href="https://fonts.googleapis.com/css2?family=Bevan&display=swap" rel="stylesheet">
    <!-- Awsome faticon -->
    <script defer src="https://use.fontawesome.com/releases/v5.0.7/js/all.js"></script>
    <!-- bootstrap scripts -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
    <script>
      function goBack() {
        window.history.back();
      }
      </script>

    <style type="text/css">
      .vypln{
          padding: 50px 0 50px 0;
      }

      body{
        background-color: #897853;
      }

      a:link {
        color: white;
        background-color: transparent;
        text-decoration: none;
      }
      </style>
  </head>
  <body>

  <section id="title">
    
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">

      <a class="navbar-brand" href="/">VAPE-G</a>

      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            {% if user.is_authenticated %}
            <li class="nav-item"><a class="nav-link" href="/onas">O nás</a></li>
            <li class="nav-item"><a class="nav-link" href="/ceny">Ceny</a></li>
            <li class="nav-item"><a class="nav-link" href="/formy">Formy</a></li>
            <li class="nav-item"><a class="nav-link" href="/food">Jídelníček</a></li>
            <li class="nav-item"><a class="nav-link" href="/training">Tréninky</a></li>
            <li class="nav-item"><a class="nav-link" href="/logout">Logout</a></li>
            {% else %}
            <li class="nav-item"><a class="nav-link" href="/onas">O nás</a></li>
            <li class="nav-item"><a class="nav-link" href="/ceny">Ceny</a></li>
            <li class="nav-item"><a class="nav-link" href="/zaregistrujse">Registrace</a></li>
            <!--<li class="nav-item"><a class="nav-link" href="/register">Registrace</a></li>-->
            <li class="nav-item"><a class="nav-link" href="/login">Login</a></li>
            {% endif %}
          </ul>
        </div>
    </nav>
    {% block content %}
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-6">
          <h1>Chceš udělat progress? Trénuj s námi!</h1>
          <button type="submit" class="btn btn-dark btn-lg"><i class="fas fa-heartbeat"></i><a color="red" href="mailto:EMAILADDRESS">Chci trenéra!</a></button>
          <button type="button" onclick="window.open('https://www.instagram.com/peta.herian/')" class="btn btn-outline-light btn-lg"><i class="fab fa-instagram"></i>Instagram</button>
        </div>
        <div class="col-lg-6  col-md-6 col-sm-12">
          <img style="height: 100%; width: 100%; object-fit: contai" src="{% static 'images/pv_1.png' %}" alt="" width="375" height="225px" class="img_pv">
        </div>
        <div class="col-lg-6 col-md-6 col-sm-12">
          <img style="height: 100%; width: 100%; object-fit: contai" src="{% static 'images/p_1.png' %}" alt="" width="375" height="225px" class="img_pv">
        </div>

      </div>
    </div>
    {% endblock%}



  </section>

  </body>
</html>

main/templates/main/ceny.html
{% extends "main/base.html" %}

{% block title %}
Ceník
{% endblock %}
{% block content %}
<H1>SKORO ZADARMO</H1>
{% endblock %}

main/templates/main/food.html
{% extends "main/base.html" %}

{% block title %}
Jídelníček
{% endblock %}

{% block content %}
<div id="content", name="content", class="main">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-2">Jídelníčky</h1>
            <hr class="mt-0 mb-4">
            {% for td in user.jidelnicek.all %}
            <a href="/{{td.id}}" class="btn btn-secondary btn-lg active" role="button" aria-pressed="true">{{td.name}}</a>
            {% endfor %}
        </div>
    </div>
</div>

{% endblock %}

main/templates/main/food_user.html
{% extends "main/base.html" %}

{% block title %}
Jídelníček
{% endblock %}

{% block content %}
{% if user.is_authenticated %}
<div id="content", name="content", class="main">
    <div class="row justify-content-center">
        <div class="col-8">
            <h1 class="mt-2">{{ls.name}}</h1>
            <hr class="mt-0 mb-4">
                {% for item in ls.jidla_set.all %}    

                <h2>{{item.text}}</h2>
                <hr class="mt-0 mb-4">

                {% endfor %}
                <button class="btn btn-dark btn-lg" onclick="goBack()">Go Back</button>
        </div>
    </div>
</div>
{% else %}
<h1>Promiň tady nic nenajdeš :(</h1>
{% endif %}
{% endblock %}

main/templates/main/formy.html
{% extends 'main/base.html' %}

{% block title%}
Formy
{% endblock %}
{% block content %}
<h1>UKAŽ FORMU!</h1>
{% endblock %}

main/templates/main/onas.html
{% extends "main/base.html" %}

{% block title %}
Ceník
{% endblock %}
{% block content %}
<h1>NATURÁLNÍ BOHOVÉ</h1>
{% endblock %}

main/templates/main/training.html
{% extends "main/base.html" %}

{% block title%}
Tréninky
{% endblock %}
{% block content %}
<h1>Dokud nebudeš brečet</h1>
{% endblock %}

main/templates/main/zaregistrujse.html
{% extends 'main/base.html' %}

{% block title%}
Formy
{% endblock %}
{% block content %}
<h1>Napiš nám proč se chceš zaregistrovat a o jaké služby máš zájem.
    <br>
    ▼▼▼
    <br>
    petis.django@seznam.cz</h1>

{% endblock %}

register/templates/register/register.html
{% extends "main/base.html" %}

{% block title %}Registrace{% endblock %}
{% load crispy_forms_tags %}

{% block content %}
<div class="vypln">
    <div class="container">
        <form method="POST" class="form-group">
            {% csrf_token %}
            {{form|crispy}}
            <button type="submit" class="btn btn-success">Register</button>
        </form>
    </div>
</div>

{% endblock %}